ktor:
    application:
        modules:
            - com.parkguard.ApplicationKt.module
    deployment:
        port: 8080

postgres:
    url: "jdbc:postgresql://localhost/default"
    user: username
    password: password